package com.shekoofe.student_management.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a student.
 * Mapped to STUDENT table in the database.
 *
 * Fields:
 * - id: autogenerated primary key
 * - name: student name, cannot be blank
 * - major: student's major
 * - age: student age, minimum 18
 *
 * @author s Bostan
 * @since Aug, 2025
 */

@Entity
@Table(name = "STUDENT")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    private String name;

    private String major;

    @Min(18)
    private int age;
}
